# The URL the site will be built for
base_url = "https://www.moystard.com"

# Theme
theme = 'butler'

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = false

title = "Jean-François 'Jeff' Moy"

description = "The personal blog of Jean-François 'Jeff' Moy, Technical Lead & Open Source Contributor. Currently VP of Engineering @ Vestiaire Collective, previously CTO @ Ksubaka."

generate_feed = true

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true
highlight_theme = "zenburn"

[extra]
butler_nav_bar = [
    {url = "$BASE_URL/blog", name = "Blog"},
    {url = "$BASE_URL/resume", name = "Resume"},
]
keywords = "software, engineer, leadership, technology, unicorn, startup, cto, vp, vice president, engineering, technology, docker, typescript, web, react, spring, kubernetes, android, kotlin, computer, java, python, moy, jean-francois, jeff, aws, devops, blog, french, london, uk, united kingdom, france"

[extra.author]
name = "Jean-Francois 'Jeff' Moy"

email.id = "jf@moy.me.uk"

twitter.username = "moystard"
twitter.link = "https://twitter.com/moystard"

subtitle = "If you can't explain it simply, you don't understand it well enough."

copyright = "Copyright Jean-Francois Moy - 2024"


